#!/bin/sh
### BEGIN INIT INFO
# Provides:          updatercd_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Setup owfs, owserver and yadoms to autostart
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting updatercd_once"
	chown -R yadoms:yadoms /opt/yadoms/ &&
	update-rc.d owfs defaults &&
	update-rc.d owserver defaults &&
	update-rc.d yadoms defaults &&
    rm /etc/init.d/updatercd_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac


